version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  node_api:
    image: nodeapp_db
    ports:
      - 3030:3030
    depends_on: 
      - mongo_db

  # Sentiment Analyzer Api Service
  sentiment_api:
    build:
      context: djangoapp/microservices
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  # Cars Inventory mongo database
  cars_inventory_db:
    container_name: carsInventory_container
    image: mongo:latest
    ports:
      - 27018:27017
    restart: always
    volumes:
      - cars_inventory_data:/data/db

  # Cars Inventory API
  cars_api:
    image: nodeapp_carsinventory
    ports:
      - 3050:3050
    depends_on:
      - cars_inventory_db

volumes:
  mongo_data: {}
  cars_inventory_data: {}